name: D365 Pipeline

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: 'Solution name'
        required: true
      sourceEnvUrl:
        description: 'Source environment URL'
        required: true
      sourceUserName:
        description: 'Source username'
        required: true

jobs:
  D365_action:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        run: |
          $env:SOLUTION_NAME = "${{ github.event.inputs.solutionName }}"
          $env:SOURCE_ENV_URL = "${{ github.event.inputs.sourceEnvUrl }}"
          $env:SOURCE_USERNAME = "${{ github.event.inputs.sourceUserName }}"
          $env:SOURCE_PASSWORD = "${{ secrets.SOURCE_PASSWORD }}"
          .\.github\scripts\run-d365-operations.ps1
